(library (gir arg)
  (export <arg> make-arg)
  (import (rnrs (6))
          (system foreign-object)
          (oop goops)
          (gir conversions)
          (gir foreign)
          (gir generics)
          (gir info)
          (gir type))

  (define-method (get-closure (arg <arg>))
    (g-arg-info-get-closure (get-ptr arg)))

  (define-method (get-type (arg <arg>))
    (make-type (g-arg-info-get-type (get-ptr arg))))
)
