(import (rnrs (6))
        (ice-9 format)
        (functional)
        (gir foreign)
        (gir info)
        (gir functions)
        (gir callables))

(let ((d   (gir-get-default))
      (gtk (gir-require "Gtk" "3.0")))
  (format #t "GIRepository search path: ~s~%" (gir-get-search-path))
  (format #t "loaded namespaces: ~s~%" (gir-get-loaded-namespaces))
  (format #t "Gtk version: ~s~%" (gir-get-version "Gtk"))
  (format #t "Gtk dependencies: ~s~%" (gir-get-dependencies "Gtk"))
  (format #t "Gtk #infos: ~s~%" (gir-get-n-infos "Gtk"))
  (format #t "Gtk prefix: ~s~%" (gir-get-c-prefix "Gtk"))
  (for-each (lambda (idx)
    (let ((info (gir-get-info "Gtk" idx)))
      (format #t "~a type: ~s ~a ~a~%"
        (gir-info-get-name info)
        (gir-info-get-type info)
        (if (eq? 'function (gir-info-get-type info))
          (gir-function-info-get-symbol info)
          "-")
        (if (eq? 'function (gir-info-get-type info))
          (gir-callable-info-get-n-args info)
          "-"))))
    (iota (gir-get-n-infos "Gtk")))
)


